### PR TITLE
Adding setAcl and getAcl methods to zkClient so users can setAcls not…

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**
… just during creation but after creation of node as well.

### CODE REVIEW

**Comment by Parth-Brahmbhatt** [comment]
One week reminder ping :-).

**Comment by jzillmann** [comment]
Hey @Parth-Brahmbhatt looks pretty good your patch. What about remove's, do you think that would be needed as well ?

**Comment by Parth-Brahmbhatt** [comment]
I don't think remove is needed, anyone who wants no acls could call set with world:crdwa to make it accessible to everyone.

**Comment by jzillmann** [comment]
Hey @Parth-Brahmbhatt could you have a look at the test it is failing for me!
Also please include a line in the changelog!

**Comment by Parth-Brahmbhatt** [comment]
@jzillmann I tried to run the tests and they are failing with timeouts. For now I have just bumped the timeouts to 30 seconds but this should not have been introduced by my change. on my box some tests fail even without my changes with timeout exceptions. Let me know if you only see these failures with my changes.

**Comment by jzillmann** [comment]
Thanks @Parth-Brahmbhatt . Tests are working now and i merged this to master!

**Comment by Parth-Brahmbhatt** [comment]
@jzillmann  Hey do you know when will you be able to release a new major/minor version with this change in it?

**Comment by jzillmann** [comment]
Hey @Parth-Brahmbhatt just pushed a 0.6 release which includes the change. Should be online within the next 24h!

**Pull request closed without merging**
