### PR TITLE
ISSUE-71: Zookeeper Client should re-resolve hosts when connection attempts fail.

### PR DESCRIPTION
**Pull request by harshach**
This issue is fixed in zookeeper client https://issues.apache.org/jira/browse/ZOOKEEPER-2184

### CODE REVIEW

**Comment by harshach** [comment]
@jzillmann we are in need of this change. Appreciate a review and release.Thanks.

**Comment by jzillmann** [comment]
@harshach So can we revert https://github.com/sgroschupf/zkclient/commit/3aa5c98377fde50c8d92f67741e3852e2c468c37 then ?

**Comment by jzillmann** [comment]
Just did that and triggered the release process for version 0.11!

**Comment by harshach** [comment]
Thank you @jzillmann

**Comment by harshach** [comment]
@jzillmann did the 0.11 release happened? I am not able to find the zkclient artifcat maven repo.

**Comment by jzillmann** [comment]
Guess something went wrong, trying to figure it out..

**Pull request merged**
