### PR TITLE
Replaced Apache Log4j with Slf4j

### PR DESCRIPTION
**Pull request by diversit**
Hi,
I am using zkclient for another project of mine, but did not like I was forced to use Apache Log4j because the ZkClient uses it.
I modified the project to use Slf4j instead so the end user can choose his own logging framework and because it's a much better logging api nowadays than log4j.

Regards,
Joost

### CODE REVIEW

**Comment by freethejazz** [comment]
Collaborators: What should be the outcome of this? Fix and merge or close and scrap?

**Comment by jzillmann** [comment]
Anyone using zkclient would have problems with this change ?

**Comment by u01iz** [comment]
I would love this change to happen :)

**Comment by wangjingfei** [comment]
I need this change too...

**Comment by tlazaro** [comment]
This would be really useful.

**Comment by benmccann** [comment]
I've put together a similar PR. It's a bit cleaner and mergable. See here: https://github.com/sgroschupf/zkclient/pull/56

**Comment by jzillmann** [comment]
Closing this one in favor of #56!

**Pull request closed without merging**
